# Generated by Django 5.2.4 on 2025-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('tailor', 'Tailor'), ('cashier', 'Cashier'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
