# Generated by Django 5.2.4 on 2025-10-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joborder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=255)),
                ('receipt_date', models.DateTimeField()),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_status', models.CharField(max_length=255)),
                ('receipt_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joborder.joborder')),
            ],
        ),
    ]
