# Generated by Django 5.2.4 on 2025-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_status',
        ),
    ]
