# Generated by Django 5.2.4 on 2025-10-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_remove_receipt_receipt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
    ]
