# Generated by Django 5.2.4 on 2025-10-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kethet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thool_kum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ardh_f_kum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jamba', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ragab', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
