# Generated by Django 5.2.4 on 2025-10-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_date_alter_sale_sale_number_and_more'),
        ('sale', '0002_alter_saleitem_sale'),
    ]

    operations = [
    ]
