# Generated by Django 5.2.4 on 2025-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='recived_on_delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
