# Generated by Django 5.2.4 on 2025-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0003_joborder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cash_bank', 'Cash Bank')], default='cash', max_length=50),
        ),
    ]
