# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0003_joborder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='joborder',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
