# Generated by Django 5.2.4 on 2025-10-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0004_alter_joborder_payment_method'),
        ('joborder', '0004_joborder_cash_card_amounts'),
    ]

    operations = [
    ]
