# Generated by Django 5.2.4 on 2025-10-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0005_merge_20251021_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cash_card', 'Cash Card')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='recived_on_delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
