# Generated by Django 5.2.4 on 2025-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0006_alter_joborder_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
