# Generated by Django 5.2.4 on 2025-11-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_name_ar', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=255)),
                ('company_website', models.URLField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='company/')),
                ('company_currency', models.CharField(max_length=255)),
                ('company_open_time', models.TimeField()),
                ('company_close_time', models.TimeField()),
                ('company_created_at', models.DateTimeField(auto_now_add=True)),
                ('company_updated_at', models.DateTimeField(auto_now=True)),
                ('company_is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
