# Generated by Django 5.2.4 on 2025-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackgroundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_route', models.CharField(help_text="Route path for the page (e.g., '/admin/dashboard', '/admin/job-orders')", max_length=255, unique=True)),
                ('page_name', models.CharField(help_text='Display name for the page', max_length=255)),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('image', 'Image'), ('gradient', 'Gradient')], default='color', help_text='Type of background to apply', max_length=20)),
                ('background_color', models.CharField(blank=True, help_text='Background color (hex code or CSS color name)', max_length=50, null=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the page', null=True, upload_to='page-backgrounds/')),
                ('background_gradient', models.CharField(blank=True, help_text="CSS gradient string (e.g., 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)')", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Background Setting',
                'verbose_name_plural': 'Page Background Settings',
                'ordering': ['page_name'],
            },
        ),
        migrations.CreateModel(
            name='SidebarItemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(help_text="Unique identifier for the sidebar item (e.g., 'dashboard', 'job-orders')", max_length=100, unique=True)),
                ('item_name', models.CharField(help_text='Display name for the sidebar item', max_length=255)),
                ('route_path', models.CharField(help_text="The route path this item should navigate to (e.g., '/admin/dashboard')", max_length=255)),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier (for reference)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which items appear in sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sidebar Item Configuration',
                'verbose_name_plural': 'Sidebar Item Configurations',
                'ordering': ['display_order', 'item_name'],
            },
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
